services:
  selenium-hub:
    image: seleniarm/hub:latest
    container_name: selenium-hub
    ports:
      - "4444:4444"
    environment:
      - GRID_MAX_SESSION=16
      - GRID_BROWSER_TIMEOUT=300
      - GRID_TIMEOUT=300

  chrome:
    image: seleniarm/node-chromium:latest
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - NODE_MAX_INSTANCES=4
      - NODE_MAX_SESSION=4
    volumes:
      - /dev/shm:/dev/shm
    scale: 2

  task-scheduler:
    build:
      context: .
      dockerfile: docker/Dockerfile.app  # 修改这里
    container_name: task-scheduler
    ports:
      - "8000:8000"
    volumes:
      - ./data/screenshots:/app/data/screenshots  # 更新路径
      - ./logs:/app/logs
      - ./config:/app/config
    environment:
      - SELENIUM_GRID_URL=http://selenium-hub:4444/wd/hub
    depends_on:
      - selenium-hub
      - chrome

  captcha-solver:
    build:
      context: .
      dockerfile: docker/Dockerfile.app  # 修改这里
    container_name: captcha-solver
    volumes:
      - ./data/screenshots:/app/data/screenshots  # 更新路径
      - ./logs:/app/logs
      - ./config:/app/config
    environment:
      - SELENIUM_GRID_URL=http://selenium-hub:4444/wd/hub
    depends_on:
      - selenium-hub
      - chrome