name: captcha-solver
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - selenium=4.15.0
  - requests=2.31.0
  - pillow=10.0.1
  - numpy=1.24.3
  - pyyaml=6.0.1
  - pip:
    - webdriver-manager==4.0.1
    - loguru==0.7.2
    - pytest==7.4.0
    - pytest-cov==4.1.0
    - black==23.7.0
    - flake8==6.0.0